#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
sudo docker build -t aeternas/swadeshness:$CIRCLE_BRANCH . && \
sudo docker push aeternas/swadeshness:$CIRCLE_BRANCH
