#!/bin/bash
go get -v -t -d ./...
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -t aeternas/swadeshness:$TRAVIS_BRANCH . && \
docker push aeternas/swadeshness:$TRAVIS_BRANCH
