aliases:
  - &get_deps go get -v -t -d ./...
  - &docker_worker
    - image: circleci/golang:1.11
  - &work_dir /go/src/github.com/aeternas/SwadeshNess
  - &git_checkout
    name: Checkout
    command: |
      mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      git clone --depth 1 -b $CIRCLE_BRANCH $CIRCLE_REPOSITORY_URL ./ && \
      git checkout $CIRCLE_SHA1
  - &update_submodules
    name: Update submodules
    command: |
      git submodule init && \
      git submodule update
  - &attach_workspace
    at: /go/src/github.com/aeternas/SwadeshNess
  - &save_cache
    key: v1-dep-{{ .Branch }}-{{ epoch }}
    paths:
    - vendor/bundle
    - ~/virtualenvs
    - ~/.m2
    - ~/.ivy2
    - ~/.bundle
    - ~/.go_workspace
    - ~/.cache/bower
  - &restore_cache
    keys:
    - v1-dep-{{ .Branch }}-
    - v1-dep-master-
    - v1-dep-
  - &persist_to_workspace
    root: .
    paths:
      - .
  - &lint
    name: Install & Execute linter
    command: |
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest && \
        golangci-lint run
  - &unit_tests
    name: Unit tests
    command: go test -v ./...
  - &setup_remote_docker
    setup_remote_docker:
      docker_layer_caching: true
  - &containerize_push_deploy
    name: Containerize, Push and Deploy
    command: |
      echo $DOCKER_PASSWORD > docker_passwd && \
      docker login -u $DOCKER_USERNAME --password-stdin < docker_passwd && rm docker_passwd && \
      docker build --build-arg VERS=$CIRCLE_BUILD_NUM -t aeternas/swadeshness:$CIRCLE_BRANCH . && \
      docker push aeternas/swadeshness:$CIRCLE_BRANCH && \
      if [[ $CIRCLE_BRANCH == "master" ]]; then \
                                      docker tag aeternas/swadeshness:master aeternas/swadeshness:latest && \
                                      docker push aeternas/swadeshness:latest; fi
  - &update_envs
    name: Update PATH and Define Environment Variable at Runtime
    command: |
      echo 'export PROD_HOST="https://$SW_PROD_BASE_URL"' >> $BASH_ENV
      echo 'export DEV_HOST="https://$SW_BASE_URL"' >> $BASH_ENV
      echo 'export BRANCH="$CIRCLE_BRANCH"' >> $BASH_ENV
      echo 'export VERSION="$CIRCLE_PREVIOUS_BUILD_NUM"' >> $BASH_ENV
  - &run_integration_tests
    name: Run Integration Tests
    command: ./SwadeshNess-IntegrationTests
  - &warm_cache
    name: Warm Cache
    command: |
      java -jar couperose-0.1.0-SNAPSHOT-standalone.jar
version: 2.1
jobs:
  checkout:
    docker: *docker_worker
    working_directory: *work_dir
    steps:
      - run: *git_checkout
      - run: *update_submodules
      - restore_cache: *restore_cache
      - run: *get_deps
      - save_cache: *save_cache
      - persist_to_workspace: *persist_to_workspace
  lint:
    docker: *docker_worker
    working_directory: *work_dir
    steps:
      - attach_workspace: *attach_workspace
      - run: *get_deps
      - run: *lint
  unit_tests:
    docker: *docker_worker
    working_directory: *work_dir
    steps:
      - attach_workspace: *attach_workspace
      - run: *get_deps
      - run: *unit_tests
  deploy:
    docker: *docker_worker
    working_directory: *work_dir
    steps:
      - attach_workspace: *attach_workspace
      - *setup_remote_docker
      - deploy: *containerize_push_deploy
  integration_tests:
    docker:
      - image: aeternas/swadeshness-tests:$CIRCLE_BRANCH
    working_directory: /
    steps:
      - run: *update_envs
      - deploy: *run_integration_tests
  warm_cache:
    docker:
      - image: aeternas/swadeshness-couperose:$CIRCLE_BRANCH
    working_directory: /home/circleci/repo
    steps:
      - deploy: *warm_cache
workflows:
  version: 2.1
  lint-test-deploy:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - unit_tests:
          requires:
            - checkout
      - deploy:
          filters:
            branches:
              only:
                - master
                - development
          requires:
            - lint
            - unit_tests
      - integration_tests:
          requires:
            - deploy
      - warm_cache:
          filters:
            branches:
              only:
                - master
          requires:
            - integration_tests
