# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  lint-test:
    docker:
      # specify the version
      - image: circleci/golang:1.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/aeternas/SwadeshNess
    steps:
      - checkout
      - restore_cache:
          keys:
          # This branch if available
          - v1-dep-{{ .Branch }}-
          # Default branch if not
          - v1-dep-master-
          # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
          - v1-dep-

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
          - vendor/bundle
          - ~/virtualenvs
          - ~/.m2
          - ~/.ivy2
          - ~/.bundle
          - ~/.go_workspace
          - ~/.gradle
          - ~/.cache/bower
      - run: 
          name: linting
          command: go install ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint && golangci-lint run
      - run:
          name: tests
          command: go test -v ./...
  deploy:
    docker:
      - image: circleci/golang:1.10
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Containerize, Push and Deploy
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker build -t aeternas/swadeshness:$CIRCLE_BRANCH . && \
            docker push aeternas/swadeshness:$CIRCLE_BRANCH
workflows:
  version: 2
  lint-test-deploy:
    jobs:
      - lint-test
      - deploy:
          requires:
            - lint-test
