_defaults: &defaults
_get_deps: &get_deps go get -v -t -d ./...

_docker_worker: &docker_worker
  - image: circleci/golang:1.11
_workdir: &work_dir /go/src/github.com/aeternas/SwadeshNess

_git_checkout: &git_checkout
  name: Checkout
  command: |
    mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    git clone --depth=50 -b $CIRCLE_BRANCH $CIRCLE_REPOSITORY_URL ./ && \
    git checkout $CIRCLE_SHA1

_attach_workspace: &attach_workspace
  at: /go/src/github.com/aeternas/SwadeshNess

version: 2
jobs:
  checkout:
    docker: *docker_worker
    working_directory: *work_dir
    steps:
      - run: *git_checkout
      - restore_cache:
          keys:
          - v1-dep-{{ .Branch }}-
          - v1-dep-master-
          - v1-dep-
      - run: *get_deps
      - save_cache:
         key: v1-dep-{{ .Branch }}-{{ epoch }}
         paths:
         - vendor/bundle
         - ~/virtualenvs
         - ~/.m2
         - ~/.ivy2
         - ~/.bundle
         - ~/.go_workspace
         - ~/.gradle
         - ~/.cache/bower
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    docker: *docker_worker
    working_directory: *work_dir
    steps:
      - attach_workspace: *attach_workspace
      - run: *get_deps
      - run: 
          name: linting
          command: go install ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint && golangci-lint run
  unit_tests:
    docker: *docker_worker
    working_directory: *work_dir
    steps:
      - attach_workspace: *attach_workspace
      - run: *get_deps
      - run:
          name: tests
          command: go test -v ./...
  deploy:
    docker: *docker_worker
    working_directory: *work_dir
    steps:
      - attach_workspace: *attach_workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - deploy:
          name: Containerize, Push and Deploy
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker build --build-arg VERS=$CIRCLE_BUILD_NUM -t aeternas/swadeshness:$CIRCLE_BRANCH . && \
            docker push aeternas/swadeshness:$CIRCLE_BRANCH
  integration_tests:
    docker:
      - image: aeternas/swadeshness-tests:$CIRCLE_BRANCH
    working_directory: /
    steps:
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            echo 'export PROD_HOST="https://vpered.su"' >> $BASH_ENV
            echo 'export DEV_HOST="https://vpered.su:8080/dev"' >> $BASH_ENV
            echo 'export BRANCH="$CIRCLE_BRANCH"' >> $BASH_ENV
            echo 'export VERSION="$CIRCLE_PREVIOUS_BUILD_NUM"' >> $BASH_ENV
      - deploy:
          name: Run Integration Tests 
          command: ./SwadeshNess-IntegrationTests
workflows:
  version: 2
  lint-test-deploy:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - unit_tests:
          requires:
            - checkout
      - deploy:
          requires:
            - lint
            - unit_tests
      - integration_tests:
          requires:
            - deploy
