name: Go

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - name: Install dependencies
        run: go install github.com/aeternas/SwadeshNess@latest
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
